<#
.SYNOPSIS
    Plan Forge — Project Setup Wizard

.DESCRIPTION
    Interactive script that bootstraps a project with the Plan Forge
    Pipeline files, instruction files, and AGENTS.md from a chosen preset.

.PARAMETER Preset
    One or more tech stack presets. Accepts a single value or a comma-separated list.
    Valid values: dotnet, typescript, python, java, go, swift, rust, php, azure-iac, custom
    Example: -Preset azure-iac                  (IaC-only repo)
    Example: -Preset dotnet,azure-iac           (app with infra folder)

.PARAMETER ProjectPath
    Target project directory. Defaults to current directory.

.PARAMETER ProjectName
    Name of the project (used in generated files).

.PARAMETER Force
    Overwrite existing files without prompting.

.PARAMETER GenericDir
    Output directory (relative to ProjectPath) for the generic AI adapter.
    Defaults to '.ai'. Used when -Agent includes 'generic'.

.EXAMPLE
    .\setup.ps1 -Preset dotnet -ProjectPath "C:\Projects\MyApp" -ProjectName "MyApp"

.EXAMPLE
    .\setup.ps1 -Preset dotnet,azure-iac -ProjectPath "C:\Projects\MyApp"  # app + infra

.EXAMPLE
    .\setup.ps1  # Interactive mode — prompts for all values
#>

param(
    [string[]]$Preset,

    [string]$ProjectPath,

    [string]$ProjectName,

    [ValidateSet('copilot', 'claude', 'cursor', 'windsurf', 'codex', 'gemini', 'generic', 'all')]
    [string[]]$Agent = @('copilot'),

    [string]$GenericDir = '.ai',

    [switch]$Force,

    [switch]$AutoDetect,

    [switch]$InstallExtensions,

    # Phase-OPENBRAIN-PROMOTION Slice 4 — suppress interactive OpenBrain prompt in CI / automation.
    # Also honored: $env:CI and $env:PFORGE_NONINTERACTIVE, plus auto-skip when stdin is not a TTY.
    [switch]$NonInteractive
)

$ErrorActionPreference = 'Stop'
$templateRoot = $PSScriptRoot

# ─── Helpers ───────────────────────────────────────────────────────────
function Write-Banner {
    Write-Host ""
    Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║       Plan Forge — Project Setup Wizard              ║" -ForegroundColor Cyan
    Write-Host "║       Bootstraps planning pipeline + tech instructions      ║" -ForegroundColor Cyan
    Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host ""
}

function Get-PromptValue([string]$Message, [string]$Default) {
    if ($Default) {
        $response = Read-Host "$Message [$Default]"
        if ([string]::IsNullOrWhiteSpace($response)) { return $Default }
        return $response
    }
    else {
        do {
            $response = Read-Host $Message
        } while ([string]::IsNullOrWhiteSpace($response))
        return $response
    }
}

function Copy-WithCreate([string]$Source, [string]$Destination, [bool]$Overwrite) {
    $destDir = Split-Path $Destination -Parent
    if (-not (Test-Path $destDir)) {
        New-Item -ItemType Directory -Path $destDir -Force | Out-Null
    }
    if ((Test-Path $Destination) -and -not $Overwrite) {
        Write-Host "  SKIP  $Destination (exists)" -ForegroundColor Yellow
        return $false
    }
    Copy-Item -Path $Source -Destination $Destination -Force
    Write-Host "  COPY  $Destination" -ForegroundColor Green
    return $true
}

function Update-Placeholders([string]$FilePath, [string]$Name, [string]$Stack) {
    if (-not (Test-Path $FilePath)) { return }
    $content = Get-Content $FilePath -Raw
    $content = $content -replace '<YOUR PROJECT NAME>', $Name
    $content = $content -replace '<YOUR TECH STACK>', $Stack
    $content = $content -replace '<YOUR BUILD COMMAND>', $BuildCmd
    $content = $content -replace '<YOUR TEST COMMAND>', $TestCmd
    $content = $content -replace '<YOUR LINT COMMAND>', $LintCmd
    $content = $content -replace '<YOUR DEV COMMAND>', ''
    $content = $content -replace '<DATE>', (Get-Date -Format 'yyyy-MM-dd')
    Set-Content -Path $FilePath -Value $content -NoNewline
}

# ─── Agent Adapter: Claude Code ────────────────────────────────────────
function Install-ClaudeAgent([string]$TargetPath) {
    Write-Host "  Installing Claude Code files..." -ForegroundColor DarkCyan

    # Generate rich CLAUDE.md — copilot-instructions + all instruction files
    $copilotInstr = Join-Path $TargetPath ".github/copilot-instructions.md"
    $claudeCtx = Join-Path $TargetPath "CLAUDE.md"
    if ((Test-Path $copilotInstr) -and -not (Test-Path $claudeCtx)) {
        $sb = [System.Text.StringBuilder]::new()
        [void]$sb.AppendLine("# Project Context for Claude")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("> Auto-generated by Plan Forge. Includes project instructions + all guardrail files.")
        [void]$sb.AppendLine("> Regenerate with: pforge smith or re-run setup with -Agent claude")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("## How to Use These Guardrails")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("This file contains domain-specific guardrails organized by section. When editing code:")
        [void]$sb.AppendLine("- Editing database/SQL/repository code → follow the **database** section")
        [void]$sb.AppendLine("- Editing auth/JWT/OIDC code → follow the **auth** section")
        [void]$sb.AppendLine("- Editing API controllers/routes → follow the **api-patterns** section")
        [void]$sb.AppendLine("- Editing tests → follow the **testing** section")
        [void]$sb.AppendLine("- Editing Docker/deploy files → follow the **deploy** section")
        [void]$sb.AppendLine("- Always follow **architecture-principles** and **security** sections")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("**After every file edit**: Scan for TODO, FIXME, HACK, stub, placeholder markers. Warn immediately if found.")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("**Before editing any file**: If a hardened plan exists in `docs/plans/`, check its Forbidden Actions section. Do not edit files listed there.")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("**Pipeline flow**: After completing a step, tell the user what to invoke next:")
        [void]$sb.AppendLine("- After Step 0 (Specify) → ``/planforge-step1-preflight-check``")
        [void]$sb.AppendLine("- After Step 2 (Harden) → ``/planforge-step3-execute-slice``")
        [void]$sb.AppendLine("- After Step 4 (Sweep) → Start a NEW session for Step 5 (Review)")
        [void]$sb.AppendLine("- After Step 5 (Review) → ``/planforge-step6-ship``")
        [void]$sb.AppendLine("")

        # Project instructions
        [void]$sb.AppendLine("## Project Instructions")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine((Get-Content $copilotInstr -Raw))
        [void]$sb.AppendLine("")

        # Embed all instruction files by domain
        $instrDir = Join-Path $TargetPath ".github/instructions"
        if (Test-Path $instrDir) {
            [void]$sb.AppendLine("---")
            [void]$sb.AppendLine("")
            [void]$sb.AppendLine("## Guardrail Files")
            [void]$sb.AppendLine("")
            [void]$sb.AppendLine("The following guardrails are auto-loaded in VS Code Copilot by file type. In Claude, they are embedded here for reference. Follow these rules when writing code.")
            [void]$sb.AppendLine("")

            Get-ChildItem -Path $instrDir -Filter "*.instructions.md" -File | Sort-Object Name | ForEach-Object {
                $domain = $_.BaseName -replace '\.instructions$', ''
                $instrContent = Get-Content $_.FullName -Raw
                # Strip YAML frontmatter for cleaner embedding
                if ($instrContent -match '^---\s*\n[\s\S]*?\n---\s*\n([\s\S]*)') {
                    $instrContent = $Matches[1].Trim()
                }
                [void]$sb.AppendLine("### $domain")
                [void]$sb.AppendLine("")
                [void]$sb.AppendLine($instrContent)
                [void]$sb.AppendLine("")
            }
        }

        Set-Content -Path $claudeCtx -Value $sb.ToString()
        Write-Host "  CREATE CLAUDE.md (project context + guardrails)" -ForegroundColor Green
    }

    # Convert ALL prompts → Claude skills (pipeline + scaffolding)
    $promptsDir = Join-Path $TargetPath ".github/prompts"
    $skillsDir = Join-Path $TargetPath ".claude/skills"
    if (Test-Path $promptsDir) {
        Get-ChildItem -Path $promptsDir -Filter "*.prompt.md" -File | ForEach-Object {
            $name = $_.BaseName -replace '\.prompt$', ''
            $skillDir = Join-Path $skillsDir "planforge-$name"
            $skillFile = Join-Path $skillDir "SKILL.md"

            if (-not (Test-Path $skillDir)) {
                New-Item -ItemType Directory -Path $skillDir -Force | Out-Null
            }

            $srcContent = Get-Content $_.FullName -Raw
            $desc = "Plan Forge prompt"
            if ($srcContent -match 'description:\s*"?([^"\n]+)"?') {
                $desc = $Matches[1].Trim()
            }

            $skillContent = @"
---
name: planforge-$name
description: $desc
metadata:
  author: plan-forge
  source: .github/prompts/$($_.Name)
user-invocable: true
argument-hint: "Provide context or parameters for this prompt"
---

$srcContent
"@
            Set-Content -Path $skillFile -Value $skillContent
            Write-Host "  CREATE .claude/skills/planforge-$name/SKILL.md" -ForegroundColor Green
        }
    }

    # Convert reviewer agents → Claude skills
    $agentsDir = Join-Path $TargetPath ".github/agents"
    if (Test-Path $agentsDir) {
        Get-ChildItem -Path $agentsDir -Filter "*.agent.md" -File | ForEach-Object {
            $name = $_.BaseName -replace '\.agent$', ''
            $skillDir = Join-Path $skillsDir "planforge-$name"
            $skillFile = Join-Path $skillDir "SKILL.md"

            if (-not (Test-Path $skillDir)) {
                New-Item -ItemType Directory -Path $skillDir -Force | Out-Null
            }

            $srcContent = Get-Content $_.FullName -Raw
            $desc = "Plan Forge reviewer agent"
            if ($srcContent -match 'description:\s*"?([^"\n]+)"?') {
                $desc = $Matches[1].Trim()
            }

            $skillContent = @"
---
name: planforge-$name
description: $desc
metadata:
  author: plan-forge
  source: .github/agents/$($_.Name)
user-invocable: true
argument-hint: "Specify files or areas to review"
---

$srcContent
"@
            Set-Content -Path $skillFile -Value $skillContent
            Write-Host "  CREATE .claude/skills/planforge-$name/SKILL.md" -ForegroundColor Green
        }
    }
}

# ─── Agent Adapter: Cursor ─────────────────────────────────────────────
function Install-CursorAgent([string]$TargetPath) {
    Write-Host "  Installing Cursor files..." -ForegroundColor DarkCyan

    # Generate rich .cursor/rules — copilot-instructions + all guardrails
    $copilotInstr = Join-Path $TargetPath ".github/copilot-instructions.md"
    $cursorRulesDir = Join-Path $TargetPath ".cursor"
    $cursorRules = Join-Path $cursorRulesDir "rules"
    if ((Test-Path $copilotInstr) -and -not (Test-Path $cursorRules)) {
        if (-not (Test-Path $cursorRulesDir)) {
            New-Item -ItemType Directory -Path $cursorRulesDir -Force | Out-Null
        }

        $sb = [System.Text.StringBuilder]::new()
        [void]$sb.AppendLine((Get-Content $copilotInstr -Raw))
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("---")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("## Plan Forge Agent Guidelines")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("When editing code, apply the guardrail section that matches the file type:")
        [void]$sb.AppendLine("- Database/SQL/ORM → **database** section | Auth/JWT → **auth** section")
        [void]$sb.AppendLine("- API routes → **api-patterns** section | Tests → **testing** section")
        [void]$sb.AppendLine("- Always follow **architecture-principles** and **security**")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("After every file edit: scan for TODO/FIXME/HACK/stub markers. Warn immediately.")
        [void]$sb.AppendLine("Before editing: check the active plan's Forbidden Actions — do not touch listed files.")
        [void]$sb.AppendLine("")

        # Embed all instruction files
        $instrDir = Join-Path $TargetPath ".github/instructions"
        if (Test-Path $instrDir) {
            [void]$sb.AppendLine("---")
            [void]$sb.AppendLine("")
            [void]$sb.AppendLine("## Guardrail Files (from Plan Forge)")
            [void]$sb.AppendLine("")

            Get-ChildItem -Path $instrDir -Filter "*.instructions.md" -File | Sort-Object Name | ForEach-Object {
                $domain = $_.BaseName -replace '\.instructions$', ''
                $instrContent = Get-Content $_.FullName -Raw
                if ($instrContent -match '^---\s*\n[\s\S]*?\n---\s*\n([\s\S]*)') {
                    $instrContent = $Matches[1].Trim()
                }
                [void]$sb.AppendLine("### $domain")
                [void]$sb.AppendLine("")
                [void]$sb.AppendLine($instrContent)
                [void]$sb.AppendLine("")
            }
        }

        Set-Content -Path $cursorRules -Value $sb.ToString()
        Write-Host "  CREATE .cursor/rules (project context + guardrails)" -ForegroundColor Green
    }

    # Convert ALL prompts → Cursor commands
    $promptsDir = Join-Path $TargetPath ".github/prompts"
    $commandsDir = Join-Path $cursorRulesDir "commands"
    if (Test-Path $promptsDir) {
        if (-not (Test-Path $commandsDir)) {
            New-Item -ItemType Directory -Path $commandsDir -Force | Out-Null
        }
        Get-ChildItem -Path $promptsDir -Filter "*.prompt.md" -File | ForEach-Object {
            $name = $_.BaseName -replace '\.prompt$', ''
            $cmdFile = Join-Path $commandsDir "planforge.$name.md"

            if (-not (Test-Path $cmdFile)) {
                $srcContent = Get-Content $_.FullName -Raw
                $desc = "Plan Forge prompt"
                if ($srcContent -match 'description:\s*"?([^"\n]+)"?') {
                    $desc = $Matches[1].Trim()
                }

                $cmdContent = @"
---
description: $desc
---

$srcContent
"@
                Set-Content -Path $cmdFile -Value $cmdContent
                Write-Host "  CREATE .cursor/commands/planforge.$name.md" -ForegroundColor Green
            }
        }
    }

    # Convert reviewer agents → Cursor commands
    $agentsDir = Join-Path $TargetPath ".github/agents"
    if (Test-Path $agentsDir) {
        if (-not (Test-Path $commandsDir)) {
            New-Item -ItemType Directory -Path $commandsDir -Force | Out-Null
        }
        Get-ChildItem -Path $agentsDir -Filter "*.agent.md" -File | ForEach-Object {
            $name = $_.BaseName -replace '\.agent$', ''
            $cmdFile = Join-Path $commandsDir "planforge.$name.md"

            if (-not (Test-Path $cmdFile)) {
                $srcContent = Get-Content $_.FullName -Raw
                $desc = "Plan Forge reviewer"
                if ($srcContent -match 'description:\s*"?([^"\n]+)"?') {
                    $desc = $Matches[1].Trim()
                }

                $cmdContent = @"
---
description: $desc
---

$srcContent
"@
                Set-Content -Path $cmdFile -Value $cmdContent
                Write-Host "  CREATE .cursor/commands/planforge.$name.md" -ForegroundColor Green
            }
        }
    }
}

# ─── Agent Adapter: Windsurf ───────────────────────────────────────────
function Install-WindsurfAgent([string]$TargetPath) {
    Write-Host "  Installing Windsurf files..." -ForegroundColor DarkCyan

    # Generate .windsurf/rules/planforge.md — copilot-instructions + all guardrails
    $copilotInstr = Join-Path $TargetPath ".github/copilot-instructions.md"
    $windsurfDir  = Join-Path $TargetPath ".windsurf"
    $rulesDir     = Join-Path $windsurfDir "rules"
    $rulesFile    = Join-Path $rulesDir "planforge.md"
    if ((Test-Path $copilotInstr) -and -not (Test-Path $rulesFile)) {
        if (-not (Test-Path $rulesDir)) {
            New-Item -ItemType Directory -Path $rulesDir -Force | Out-Null
        }

        $sb = [System.Text.StringBuilder]::new()
        [void]$sb.AppendLine((Get-Content $copilotInstr -Raw))
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("---")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("## Plan Forge Agent Guidelines")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("When editing code, apply the guardrail section that matches the file type:")
        [void]$sb.AppendLine("- Database/SQL/ORM → **database** section | Auth/JWT → **auth** section")
        [void]$sb.AppendLine("- API routes → **api-patterns** section | Tests → **testing** section")
        [void]$sb.AppendLine("- Always follow **architecture-principles** and **security**")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("After every file edit: scan for TODO/FIXME/HACK/stub markers. Warn immediately.")
        [void]$sb.AppendLine("Before editing: check the active plan's Forbidden Actions — do not touch listed files.")
        [void]$sb.AppendLine("")

        # Embed all instruction files
        $instrDir = Join-Path $TargetPath ".github/instructions"
        if (Test-Path $instrDir) {
            [void]$sb.AppendLine("---")
            [void]$sb.AppendLine("")
            [void]$sb.AppendLine("## Guardrail Files (from Plan Forge)")
            [void]$sb.AppendLine("")

            Get-ChildItem -Path $instrDir -Filter "*.instructions.md" -File | Sort-Object Name | ForEach-Object {
                $domain = $_.BaseName -replace '\.instructions$', ''
                $instrContent = Get-Content $_.FullName -Raw
                if ($instrContent -match '^---\s*\n[\s\S]*?\n---\s*\n([\s\S]*)') {
                    $instrContent = $Matches[1].Trim()
                }
                [void]$sb.AppendLine("### $domain")
                [void]$sb.AppendLine("")
                [void]$sb.AppendLine($instrContent)
                [void]$sb.AppendLine("")
            }
        }

        Set-Content -Path $rulesFile -Value $sb.ToString()
        Write-Host "  CREATE .windsurf/rules/planforge.md (project context + guardrails)" -ForegroundColor Green
    }

    # Convert ALL prompts → Windsurf workflows
    $promptsDir   = Join-Path $TargetPath ".github/prompts"
    $workflowsDir = Join-Path $windsurfDir "workflows"
    if (Test-Path $promptsDir) {
        if (-not (Test-Path $workflowsDir)) {
            New-Item -ItemType Directory -Path $workflowsDir -Force | Out-Null
        }
        Get-ChildItem -Path $promptsDir -Filter "*.prompt.md" -File | ForEach-Object {
            $name    = $_.BaseName -replace '\.prompt$', ''
            $wfFile  = Join-Path $workflowsDir "planforge.$name.md"

            if (-not (Test-Path $wfFile)) {
                $srcContent = Get-Content $_.FullName -Raw
                $desc = "Plan Forge prompt"
                if ($srcContent -match 'description:\s*"?([^"\n]+)"?') {
                    $desc = $Matches[1].Trim()
                }

                $wfContent = @"
---
description: $desc
---

$srcContent
"@
                Set-Content -Path $wfFile -Value $wfContent
                Write-Host "  CREATE .windsurf/workflows/planforge.$name.md" -ForegroundColor Green
            }
        }
    }

    # Convert reviewer agents → Windsurf workflows
    $agentsDir = Join-Path $TargetPath ".github/agents"
    if (Test-Path $agentsDir) {
        if (-not (Test-Path $workflowsDir)) {
            New-Item -ItemType Directory -Path $workflowsDir -Force | Out-Null
        }
        Get-ChildItem -Path $agentsDir -Filter "*.agent.md" -File | ForEach-Object {
            $name   = $_.BaseName -replace '\.agent$', ''
            $wfFile = Join-Path $workflowsDir "planforge.$name.md"

            if (-not (Test-Path $wfFile)) {
                $srcContent = Get-Content $_.FullName -Raw
                $desc = "Plan Forge reviewer"
                if ($srcContent -match 'description:\s*"?([^"\n]+)"?') {
                    $desc = $Matches[1].Trim()
                }

                $wfContent = @"
---
description: $desc
---

$srcContent
"@
                Set-Content -Path $wfFile -Value $wfContent
                Write-Host "  CREATE .windsurf/workflows/planforge.$name.md" -ForegroundColor Green
            }
        }
    }
}

# ─── Agent Adapter: Codex CLI ──────────────────────────────────────────
function Install-CodexAgent([string]$TargetPath) {
    Write-Host "  Installing Codex CLI files..." -ForegroundColor DarkCyan

    # Convert ALL prompts → Codex skills
    $promptsDir = Join-Path $TargetPath ".github/prompts"
    $skillsDir = Join-Path $TargetPath ".agents/skills"
    if (Test-Path $promptsDir) {
        Get-ChildItem -Path $promptsDir -Filter "*.prompt.md" -File | ForEach-Object {
            $name = $_.BaseName -replace '\.prompt$', ''
            $skillDir = Join-Path $skillsDir "planforge-$name"
            $skillFile = Join-Path $skillDir "SKILL.md"

            if (-not (Test-Path $skillDir)) {
                New-Item -ItemType Directory -Path $skillDir -Force | Out-Null
            }

            $srcContent = Get-Content $_.FullName -Raw
            $desc = "Plan Forge prompt"
            if ($srcContent -match 'description:\s*"?([^"\n]+)"?') {
                $desc = $Matches[1].Trim()
            }

            $skillContent = @"
---
name: planforge-$name
description: $desc
metadata:
  author: plan-forge
  source: .github/prompts/$($_.Name)
---

$srcContent
"@
            Set-Content -Path $skillFile -Value $skillContent
            Write-Host "  CREATE .agents/skills/planforge-$name/SKILL.md" -ForegroundColor Green
        }
    }

    # Convert reviewer agents → Codex skills
    $agentsDir = Join-Path $TargetPath ".github/agents"
    if (Test-Path $agentsDir) {
        Get-ChildItem -Path $agentsDir -Filter "*.agent.md" -File | ForEach-Object {
            $name = $_.BaseName -replace '\.agent$', ''
            $skillDir = Join-Path $skillsDir "planforge-$name"
            $skillFile = Join-Path $skillDir "SKILL.md"

            if (-not (Test-Path $skillDir)) {
                New-Item -ItemType Directory -Path $skillDir -Force | Out-Null
            }

            $srcContent = Get-Content $_.FullName -Raw
            $desc = "Plan Forge reviewer"
            if ($srcContent -match 'description:\s*"?([^"\n]+)"?') {
                $desc = $Matches[1].Trim()
            }

            $skillContent = @"
---
name: planforge-$name
description: $desc
metadata:
  author: plan-forge
  source: .github/agents/$($_.Name)
---

$srcContent
"@
            Set-Content -Path $skillFile -Value $skillContent
            Write-Host "  CREATE .agents/skills/planforge-$name/SKILL.md" -ForegroundColor Green
        }
    }
}

# ─── Agent Adapter: Gemini CLI ─────────────────────────────────────────
function Install-GeminiAgent([string]$TargetPath) {
    Write-Host "  Installing Gemini CLI files..." -ForegroundColor DarkCyan

    # Generate GEMINI.md — uses @import syntax to pull in instruction files
    $copilotInstr = Join-Path $TargetPath ".github/copilot-instructions.md"
    $geminiCtx = Join-Path $TargetPath "GEMINI.md"
    if ((Test-Path $copilotInstr) -and -not (Test-Path $geminiCtx)) {
        $sb = [System.Text.StringBuilder]::new()
        [void]$sb.AppendLine("# Project Context for Gemini CLI")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("> Auto-generated by Plan Forge. Includes project instructions + guardrail imports.")
        [void]$sb.AppendLine("> Regenerate with: re-run setup with -Agent gemini")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("## How to Use These Guardrails")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("This file contains domain-specific guardrails organized by section. When editing code:")
        [void]$sb.AppendLine("- Editing database/SQL/repository code → follow the **database** section")
        [void]$sb.AppendLine("- Editing auth/JWT/OIDC code → follow the **auth** section")
        [void]$sb.AppendLine("- Editing API controllers/routes → follow the **api-patterns** section")
        [void]$sb.AppendLine("- Editing tests → follow the **testing** section")
        [void]$sb.AppendLine("- Editing Docker/deploy files → follow the **deploy** section")
        [void]$sb.AppendLine("- Always follow **architecture-principles** and **security** sections")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("**After every file edit**: Scan for TODO, FIXME, HACK, stub, placeholder markers. Warn immediately if found.")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("**Before editing any file**: If a hardened plan exists in ``docs/plans/``, check its Forbidden Actions section. Do not edit files listed there.")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("**Pipeline flow**: After completing a step, tell the user what to invoke next:")
        [void]$sb.AppendLine("- After Step 0 (Specify) → ``/planforge:step1-preflight-check``")
        [void]$sb.AppendLine("- After Step 2 (Harden) → ``/planforge:step3-execute-slice``")
        [void]$sb.AppendLine("- After Step 4 (Sweep) → Start a NEW session for Step 5 (Review)")
        [void]$sb.AppendLine("- After Step 5 (Review) → ``/planforge:step6-ship``")
        [void]$sb.AppendLine("")

        # Project instructions
        [void]$sb.AppendLine("## Project Instructions")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine((Get-Content $copilotInstr -Raw))
        [void]$sb.AppendLine("")

        # Import guardrail files using Gemini's @import syntax
        $instrDir = Join-Path $TargetPath ".github/instructions"
        if (Test-Path $instrDir) {
            [void]$sb.AppendLine("---")
            [void]$sb.AppendLine("")
            [void]$sb.AppendLine("## Guardrail Files")
            [void]$sb.AppendLine("")
            [void]$sb.AppendLine("The following guardrails are imported from Plan Forge instruction files. Gemini CLI auto-loads these via ``@`` imports.")
            [void]$sb.AppendLine("")

            Get-ChildItem -Path $instrDir -Filter "*.instructions.md" -File | Sort-Object Name | ForEach-Object {
                $domain = $_.BaseName -replace '\.instructions$', ''
                $relativePath = ".github/instructions/$($_.Name)"
                [void]$sb.AppendLine("### $domain")
                [void]$sb.AppendLine("")
                [void]$sb.AppendLine("@$relativePath")
                [void]$sb.AppendLine("")
            }
        }

        Set-Content -Path $geminiCtx -Value $sb.ToString()
        Write-Host "  CREATE GEMINI.md (project context + guardrail imports)" -ForegroundColor Green
    }

    # Convert ALL prompts → Gemini CLI commands (.toml)
    $promptsDir = Join-Path $TargetPath ".github/prompts"
    $geminiDir = Join-Path $TargetPath ".gemini"
    $commandsDir = Join-Path $geminiDir "commands/planforge"
    if (Test-Path $promptsDir) {
        if (-not (Test-Path $commandsDir)) {
            New-Item -ItemType Directory -Path $commandsDir -Force | Out-Null
        }
        Get-ChildItem -Path $promptsDir -Filter "*.prompt.md" -File | ForEach-Object {
            $name = $_.BaseName -replace '\.prompt$', ''
            $tomlFile = Join-Path $commandsDir "$name.toml"

            if (-not (Test-Path $tomlFile)) {
                $srcContent = Get-Content $_.FullName -Raw
                $desc = "Plan Forge prompt"
                if ($srcContent -match 'description:\s*"?([^"\n]+)"?') {
                    $desc = $Matches[1].Trim()
                }
                # Strip YAML frontmatter for TOML prompt
                $promptBody = $srcContent
                if ($promptBody -match '^---\s*\n[\s\S]*?\n---\s*\n([\s\S]*)') {
                    $promptBody = $Matches[1].Trim()
                }
                # Escape TOML triple-quote edge cases
                $promptBody = $promptBody -replace '"""', '\"\"\"'

                $tomlLines = @(
                    "# Invoked via: /planforge:$name"
                    "description = `"$($desc -replace '"', '\"')`""
                    ""
                    'prompt = """'
                )
                $tomlLines += $promptBody -split "`n"
                $tomlLines += '"""'
                Set-Content -Path $tomlFile -Value ($tomlLines -join "`n")
                Write-Host "  CREATE .gemini/commands/planforge/$name.toml" -ForegroundColor Green
            }
        }
    }

    # Convert reviewer agents → Gemini CLI commands (.toml)
    $agentsDir = Join-Path $TargetPath ".github/agents"
    if (Test-Path $agentsDir) {
        if (-not (Test-Path $commandsDir)) {
            New-Item -ItemType Directory -Path $commandsDir -Force | Out-Null
        }
        Get-ChildItem -Path $agentsDir -Filter "*.agent.md" -File | ForEach-Object {
            $name = $_.BaseName -replace '\.agent$', ''
            $tomlFile = Join-Path $commandsDir "$name.toml"

            if (-not (Test-Path $tomlFile)) {
                $srcContent = Get-Content $_.FullName -Raw
                $desc = "Plan Forge reviewer"
                if ($srcContent -match 'description:\s*"?([^"\n]+)"?') {
                    $desc = $Matches[1].Trim()
                }
                # Strip YAML frontmatter
                $promptBody = $srcContent
                if ($promptBody -match '^---\s*\n[\s\S]*?\n---\s*\n([\s\S]*)') {
                    $promptBody = $Matches[1].Trim()
                }
                $promptBody = $promptBody -replace '"""', '\"\"\"'

                $tomlLines = @(
                    "# Invoked via: /planforge:$name"
                    "description = `"$($desc -replace '"', '\"')`""
                    ""
                    'prompt = """'
                )
                $tomlLines += $promptBody -split "`n"
                $tomlLines += '"""'
                Set-Content -Path $tomlFile -Value ($tomlLines -join "`n")
                Write-Host "  CREATE .gemini/commands/planforge/$name.toml" -ForegroundColor Green
            }
        }
    }

    # Generate .gemini/settings.json with MCP server config (if applicable)
    $settingsFile = Join-Path $geminiDir "settings.json"
    if (-not (Test-Path $settingsFile)) {
        if (-not (Test-Path $geminiDir)) {
            New-Item -ItemType Directory -Path $geminiDir -Force | Out-Null
        }
        $settings = @{
            theme = "Default"
            mcpServers = @{
                "plan-forge" = @{
                    command = "node"
                    args = @("pforge-mcp/server.mjs")
                    cwd = $TargetPath
                }
            }
        } | ConvertTo-Json -Depth 4
        Set-Content -Path $settingsFile -Value $settings
        Write-Host "  CREATE .gemini/settings.json (MCP server config)" -ForegroundColor Green
    }
}

# ─── Agent Adapter: Generic (any AI coding assistant) ──────────────────
function Install-GenericAgent([string]$TargetPath, [string]$GenericDir = '.ai') {
    Write-Host "  Installing Generic AI adapter files (dir: $GenericDir)..." -ForegroundColor DarkCyan

    $outputDir = Join-Path $TargetPath $GenericDir
    if (-not (Test-Path $outputDir)) {
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
    }

    # Generate AI_INSTRUCTIONS.md — full context + all guardrails embedded inline
    $copilotInstr = Join-Path $TargetPath ".github/copilot-instructions.md"
    $aiCtx = Join-Path $outputDir "AI_INSTRUCTIONS.md"
    if ((Test-Path $copilotInstr) -and -not (Test-Path $aiCtx)) {
        $sb = [System.Text.StringBuilder]::new()
        [void]$sb.AppendLine("# Project Context for AI Coding Assistants")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("> Auto-generated by Plan Forge. Load this file into your AI assistant's context.")
        [void]$sb.AppendLine("> Regenerate with: re-run setup with -Agent generic")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("## How to Use These Guardrails")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("This file contains domain-specific guardrails organized by section. When editing code:")
        [void]$sb.AppendLine("- Editing database/SQL/repository code → follow the **database** section")
        [void]$sb.AppendLine("- Editing auth/JWT/OIDC code → follow the **auth** section")
        [void]$sb.AppendLine("- Editing API controllers/routes → follow the **api-patterns** section")
        [void]$sb.AppendLine("- Editing tests → follow the **testing** section")
        [void]$sb.AppendLine("- Editing Docker/deploy files → follow the **deploy** section")
        [void]$sb.AppendLine("- Always follow **architecture-principles** and **security** sections")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("**After every file edit**: Scan for TODO, FIXME, HACK, stub, placeholder markers. Warn immediately if found.")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("**Before editing any file**: If a hardened plan exists in ``docs/plans/``, check its Forbidden Actions section. Do not edit files listed there.")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("**Pipeline flow**: After completing a step, tell the user what to invoke next:")
        [void]$sb.AppendLine("- After Step 0 (Specify) → run step1-preflight-check")
        [void]$sb.AppendLine("- After Step 2 (Harden) → run step3-execute-slice")
        [void]$sb.AppendLine("- After Step 4 (Sweep) → Start a NEW session for Step 5 (Review)")
        [void]$sb.AppendLine("- After Step 5 (Review) → run step6-ship")
        [void]$sb.AppendLine("")

        # Project instructions
        [void]$sb.AppendLine("## Project Instructions")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine((Get-Content $copilotInstr -Raw))
        [void]$sb.AppendLine("")

        # Embed all instruction files inline
        $instrDir = Join-Path $TargetPath ".github/instructions"
        if (Test-Path $instrDir) {
            [void]$sb.AppendLine("---")
            [void]$sb.AppendLine("")
            [void]$sb.AppendLine("## Guardrail Files")
            [void]$sb.AppendLine("")
            [void]$sb.AppendLine("The following guardrails are embedded from Plan Forge instruction files.")
            [void]$sb.AppendLine("")

            Get-ChildItem -Path $instrDir -Filter "*.instructions.md" -File | Sort-Object Name | ForEach-Object {
                $domain = $_.BaseName -replace '\.instructions$', ''
                $instrContent = Get-Content $_.FullName -Raw
                if ($instrContent -match '^---\s*\n[\s\S]*?\n---\s*\n([\s\S]*)') {
                    $instrContent = $Matches[1].Trim()
                }
                [void]$sb.AppendLine("### $domain")
                [void]$sb.AppendLine("")
                [void]$sb.AppendLine($instrContent)
                [void]$sb.AppendLine("")
            }
        }

        Set-Content -Path $aiCtx -Value $sb.ToString()
        Write-Host "  CREATE $GenericDir/AI_INSTRUCTIONS.md (project context + guardrails)" -ForegroundColor Green
    }

    # Copy prompts as plain markdown files
    $promptsDir = Join-Path $TargetPath ".github/prompts"
    $promptsDst = Join-Path $outputDir "prompts"
    if (Test-Path $promptsDir) {
        if (-not (Test-Path $promptsDst)) {
            New-Item -ItemType Directory -Path $promptsDst -Force | Out-Null
        }
        Get-ChildItem -Path $promptsDir -Filter "*.prompt.md" -File | ForEach-Object {
            $dst = Join-Path $promptsDst $_.Name
            if (-not (Test-Path $dst)) {
                Copy-Item -Path $_.FullName -Destination $dst
                Write-Host "  COPY  $GenericDir/prompts/$($_.Name)" -ForegroundColor Green
            }
        }
    }

    # Copy agent definition files as plain markdown files
    $agentsDir = Join-Path $TargetPath ".github/agents"
    $agentsDst = Join-Path $outputDir "agents"
    if (Test-Path $agentsDir) {
        if (-not (Test-Path $agentsDst)) {
            New-Item -ItemType Directory -Path $agentsDst -Force | Out-Null
        }
        Get-ChildItem -Path $agentsDir -Filter "*.agent.md" -File | ForEach-Object {
            $dst = Join-Path $agentsDst $_.Name
            if (-not (Test-Path $dst)) {
                Copy-Item -Path $_.FullName -Destination $dst
                Write-Host "  COPY  $GenericDir/agents/$($_.Name)" -ForegroundColor Green
            }
        }
    }
}

function Find-Preset([string]$TargetPath) {
    # .NET markers
    $hasCsproj = $null -ne (Get-ChildItem -Path $TargetPath -Filter "*.csproj" -Recurse -Depth 2 -ErrorAction SilentlyContinue | Select-Object -First 1)
    $hasSln    = $null -ne (Get-ChildItem -Path $TargetPath -Filter "*.sln" -Recurse -Depth 1 -ErrorAction SilentlyContinue | Select-Object -First 1)
    $hasFsproj = $null -ne (Get-ChildItem -Path $TargetPath -Filter "*.fsproj" -Recurse -Depth 2 -ErrorAction SilentlyContinue | Select-Object -First 1)

    # Python markers
    $hasPyproject    = Test-Path (Join-Path $TargetPath "pyproject.toml")
    $hasRequirements = Test-Path (Join-Path $TargetPath "requirements.txt")
    $hasSetupPy      = Test-Path (Join-Path $TargetPath "setup.py")
    $hasPipfile      = Test-Path (Join-Path $TargetPath "Pipfile")

    # Java markers
    $hasPom        = Test-Path (Join-Path $TargetPath "pom.xml")
    $hasBuildGradle = Test-Path (Join-Path $TargetPath "build.gradle")
    $hasBuildGradleKts = Test-Path (Join-Path $TargetPath "build.gradle.kts")

    # Go markers
    $hasGoMod = Test-Path (Join-Path $TargetPath "go.mod")

    # Swift markers
    $hasPackageSwift = Test-Path (Join-Path $TargetPath "Package.swift")
    $hasXcodeproj   = $null -ne (Get-ChildItem -Path $TargetPath -Filter "*.xcodeproj" -Depth 1 -ErrorAction SilentlyContinue | Select-Object -First 1)
    $hasXcworkspace = $null -ne (Get-ChildItem -Path $TargetPath -Filter "*.xcworkspace" -Depth 1 -ErrorAction SilentlyContinue | Select-Object -First 1)

    # Rust markers
    $hasCargoToml = Test-Path (Join-Path $TargetPath "Cargo.toml")

    # PHP markers
    $hasComposerJson = Test-Path (Join-Path $TargetPath "composer.json")
    $hasArtisan      = Test-Path (Join-Path $TargetPath "artisan")

    # Node/TypeScript markers
    $hasPackageJson = Test-Path (Join-Path $TargetPath "package.json")
    $hasTsConfig    = Test-Path (Join-Path $TargetPath "tsconfig.json")

    # Azure IaC markers
    $hasBicep     = $null -ne (Get-ChildItem -Path $TargetPath -Filter "*.bicep" -Recurse -Depth 3 -ErrorAction SilentlyContinue | Select-Object -First 1)
    $hasAzureYaml = Test-Path (Join-Path $TargetPath "azure.yaml")
    $hasBicepConfig = Test-Path (Join-Path $TargetPath "bicepconfig.json")
    $hasTf        = $null -ne (Get-ChildItem -Path $TargetPath -Filter "*.tf" -Recurse -Depth 3 -ErrorAction SilentlyContinue | Select-Object -First 1)

    if ($hasCsproj -or $hasSln -or $hasFsproj) {
        Write-Host "  AUTO-DETECT  Found .NET project markers" -ForegroundColor Magenta
        return 'dotnet'
    }
    if ($hasGoMod) {
        Write-Host "  AUTO-DETECT  Found Go project markers" -ForegroundColor Magenta
        return 'go'
    }
    if ($hasPackageSwift -or $hasXcodeproj -or $hasXcworkspace) {
        Write-Host "  AUTO-DETECT  Found Swift project markers" -ForegroundColor Magenta
        return 'swift'
    }
    if ($hasCargoToml) {
        Write-Host "  AUTO-DETECT  Found Rust project markers" -ForegroundColor Magenta
        return 'rust'
    }
    if ($hasPom -or $hasBuildGradle -or $hasBuildGradleKts) {
        Write-Host "  AUTO-DETECT  Found Java project markers" -ForegroundColor Magenta
        return 'java'
    }
    if ($hasPyproject -or $hasRequirements -or $hasSetupPy -or $hasPipfile) {
        Write-Host "  AUTO-DETECT  Found Python project markers" -ForegroundColor Magenta
        return 'python'
    }
    if ($hasPackageJson -or $hasTsConfig) {
        Write-Host "  AUTO-DETECT  Found TypeScript/Node project markers" -ForegroundColor Magenta
        return 'typescript'
    }
    if ($hasComposerJson -or $hasArtisan) {
        Write-Host "  AUTO-DETECT  Found PHP/Laravel project markers" -ForegroundColor Magenta
        return 'php'
    }
    if ($hasBicep -or $hasAzureYaml -or $hasBicepConfig -or $hasTf) {
        Write-Host "  AUTO-DETECT  Found Azure IaC project markers" -ForegroundColor Magenta
        return 'azure-iac'
    }

    Write-Host "  AUTO-DETECT  No known markers found — using 'custom'" -ForegroundColor Yellow
    return 'custom'
}

# ─── Interactive Prompts ───────────────────────────────────────────────
Write-Banner

if (-not $ProjectPath) {
    $ProjectPath = Get-PromptValue "Target project directory" (Get-Location).Path
}
$ProjectPath = (Resolve-Path $ProjectPath -ErrorAction SilentlyContinue)?.Path ?? $ProjectPath

if (-not (Test-Path $ProjectPath)) {
    Write-Host "Creating directory: $ProjectPath" -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $ProjectPath -Force | Out-Null
}

# ─── Spec Kit Detection ───────────────────────────────────────────────
$specKitLines = @()
$specsDir = Join-Path $ProjectPath "specs"
if (Test-Path $specsDir) {
    foreach ($sf in (Get-ChildItem -Path $specsDir -Recurse -Filter "spec.md" -File -ErrorAction SilentlyContinue | Select-Object -First 5)) {
        $specKitLines += "  • $($sf.FullName.Substring($ProjectPath.Length + 1)) — feature specification"
    }
    foreach ($pf in (Get-ChildItem -Path $specsDir -Recurse -Filter "plan.md" -File -ErrorAction SilentlyContinue | Select-Object -First 5)) {
        $specKitLines += "  • $($pf.FullName.Substring($ProjectPath.Length + 1)) — implementation plan"
    }
    foreach ($tf in (Get-ChildItem -Path $specsDir -Recurse -Filter "tasks.md" -File -ErrorAction SilentlyContinue | Select-Object -First 5)) {
        $specKitLines += "  • $($tf.FullName.Substring($ProjectPath.Length + 1)) — task breakdown"
    }
}
$constitutionPath = Join-Path $ProjectPath "memory/constitution.md"
if (Test-Path $constitutionPath) {
    $specKitLines += "  • memory/constitution.md — project constitution"
}
if ($specKitLines.Count -gt 0) {
    Write-Host ""
    Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Magenta
    Write-Host "║       Spec Kit Artifacts Detected                          ║" -ForegroundColor Magenta
    Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Magenta
    Write-Host ""
    Write-Host "Found Spec Kit artifacts in this project:" -ForegroundColor Magenta
    $specKitLines | ForEach-Object { Write-Host $_ -ForegroundColor Magenta }
    Write-Host ""
    Write-Host "Plan Forge will complement your Spec Kit workflow:" -ForegroundColor Cyan
    Write-Host "  - Spec Kit defines WHAT to build"
    Write-Host "  - Plan Forge hardens specs into execution contracts with validation gates"
    Write-Host "  - To import a spec: open docs/plans/AI-Plan-Hardening-Runbook-Instructions.md after setup"
    Write-Host ""
}

if (-not $ProjectName) {
    $defaultName = Split-Path $ProjectPath -Leaf
    $ProjectName = Get-PromptValue "Project name" $defaultName
}

# Normalise: accept comma-separated string as well as array
if ($Preset.Count -eq 1 -and $Preset[0] -match ',') {
    $Preset = $Preset[0] -split ',' | ForEach-Object { $_.Trim() }
}

$validPresets = @('dotnet','typescript','python','java','go','swift','rust','php','azure-iac','custom')
foreach ($p in $Preset) {
    if ($p -notin $validPresets) {
        Write-Host "  ERROR  Unknown preset '$p'. Valid values: $($validPresets -join ', ')" -ForegroundColor Red
        exit 1
    }
}

if (-not $Preset) {
    if ($AutoDetect) {
        Write-Host ""
        Write-Host "Auto-detecting tech stack..." -ForegroundColor Cyan
        $Preset = Find-Preset $ProjectPath
        if (-not $Force) {
            $confirmPreset = Read-Host "Detected preset: $Preset. Is this correct? (Y/n)"
            if ($confirmPreset -and $confirmPreset -notin @('y', 'Y', 'yes', 'Yes', '')) {
                Write-Host ""
                Write-Host "Available presets:" -ForegroundColor Cyan
                Write-Host "  1) dotnet      — .NET / C# / ASP.NET Core"
                Write-Host "  2) typescript  — TypeScript / React / Node.js / Express"
                Write-Host "  3) python      — Python / FastAPI / SQLAlchemy"
                Write-Host "  4) java        — Java / Spring Boot / Gradle / Maven"
                Write-Host "  5) go          — Go / Chi / Gin / Standard Library"
                Write-Host "  6) swift       — Swift / SwiftUI / iOS / Vapor"
                Write-Host "  7) azure-iac   — Azure Bicep / Terraform / PowerShell / azd"
                Write-Host "  8) custom      — Shared files only (add your own instructions)"
                Write-Host ""
                $choice = Get-PromptValue "Select preset (1-8 or name)" "1"
                $Preset = switch ($choice) {
                    '1' { 'dotnet' }
                    '2' { 'typescript' }
                    '3' { 'python' }
                    '4' { 'java' }
                    '5' { 'go' }
                    '6' { 'swift' }
                    '7' { 'azure-iac' }
                    '8' { 'custom' }
                    default { $choice }
                }
            }
        }
    }
    else {
        Write-Host ""
        Write-Host "Available presets:" -ForegroundColor Cyan
        Write-Host "  1) dotnet      — .NET / C# / ASP.NET Core"
        Write-Host "  2) typescript  — TypeScript / React / Node.js / Express"
        Write-Host "  3) python      — Python / FastAPI / SQLAlchemy"
        Write-Host "  4) java        — Java / Spring Boot / Gradle / Maven"
        Write-Host "  5) go          — Go / Chi / Gin / Standard Library"
        Write-Host "  6) swift       — Swift / SwiftUI / iOS / Vapor"
        Write-Host "  7) azure-iac   — Azure Bicep / Terraform / PowerShell / azd"
        Write-Host "  8) custom      — Shared files only (add your own instructions)"
        Write-Host ""
        $choice = Get-PromptValue "Select preset (1-8 or name)" "1"
        $Preset = switch ($choice) {
            '1' { 'dotnet' }
            '2' { 'typescript' }
            '3' { 'python' }
            '4' { 'java' }
            '5' { 'go' }
            '6' { 'swift' }
            '7' { 'azure-iac' }
            '8' { 'custom' }
            default { $choice }
        }
    }
}

$stackLabel = if ($Preset.Count -gt 1) {
    ($Preset | ForEach-Object {
        switch ($_) {
            'dotnet'     { '.NET' }
            'typescript' { 'TypeScript' }
            'python'     { 'Python' }
            'java'       { 'Java' }
            'go'         { 'Go' }
            'swift'      { 'Swift' }
            'azure-iac'  { 'Azure IaC' }
            'custom'     { 'Custom' }
        }
    }) -join ' + '
} else {
    switch ($Preset[0]) {
        'dotnet'     { '.NET / C# / ASP.NET Core' }
        'typescript' { 'TypeScript / React / Node.js' }
        'python'     { 'Python / FastAPI' }
        'java'       { 'Java / Spring Boot' }
        'go'         { 'Go / Standard Library' }
        'swift'      { 'Swift / SwiftUI / iOS / Vapor' }
        'azure-iac'  { 'Azure Bicep / Terraform / PowerShell / azd' }
        'custom'     { 'Custom (configure manually)' }
    }
}

# Primary preset drives build/test/lint defaults (first non-custom wins)
$primaryPreset = ($Preset | Where-Object { $_ -ne 'custom' } | Select-Object -First 1) ?? 'custom'

# ─── Build/Test/Lint Commands ──────────────────────────────────────────
$defaultBuild = switch ($primaryPreset) {
    'dotnet'     { 'dotnet build' }
    'typescript' { 'pnpm build' }
    'python'     { 'python -m build' }
    'java'       { './gradlew build' }
    'go'         { 'go build ./...' }
    'swift'      { 'swift build' }
    'azure-iac'  { 'az bicep build --file infra/main.bicep' }
    'custom'     { '' }
}
$defaultTest = switch ($primaryPreset) {
    'dotnet'     { 'dotnet test' }
    'typescript' { 'pnpm test' }
    'python'     { 'pytest' }
    'java'       { './gradlew test' }
    'go'         { 'go test ./...' }
    'swift'      { 'swift test' }
    'azure-iac'  { 'Invoke-Pester -Path ./tests -Output Detailed' }
    'custom'     { '' }
}
$defaultLint = switch ($primaryPreset) {
    'dotnet'     { 'dotnet format --verify-no-changes' }
    'typescript' { 'pnpm lint' }
    'python'     { 'ruff check .' }
    'java'       { './gradlew spotlessCheck' }
    'go'         { 'golangci-lint run' }
    'swift'      { 'swift package plugin --allow-writing-to-package-directory swiftlint' }
    'azure-iac'  { 'az bicep lint --file infra/main.bicep' }
    'custom'     { '' }
}

if (-not $Force) {
    Write-Host ""
    Write-Host "Build/Test/Lint commands (press Enter for defaults):" -ForegroundColor Cyan
    $BuildCmd = Get-PromptValue "Build command" $defaultBuild
    $TestCmd  = Get-PromptValue "Test command" $defaultTest
    $LintCmd  = Get-PromptValue "Lint command" $defaultLint
}
else {
    $BuildCmd = $defaultBuild
    $TestCmd  = $defaultTest
    $LintCmd  = $defaultLint
}

# ─── Summary ───────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Configuration:" -ForegroundColor Cyan
Write-Host "  Project:  $ProjectName"
Write-Host "  Path:     $ProjectPath"
Write-Host "  Preset(s): $($Preset -join ', ') ($stackLabel)"
Write-Host "  Build:    $BuildCmd"
Write-Host "  Test:     $TestCmd"
Write-Host "  Lint:     $LintCmd"
Write-Host "  Force:    $Force"
Write-Host ""

if (-not $Force) {
    $confirm = Read-Host "Proceed? (Y/n)"
    if ($confirm -and $confirm -notin @('y', 'Y', 'yes', 'Yes', '')) {
        Write-Host "Aborted." -ForegroundColor Red
        exit 0
    }
}

# ─── Step 1: Copy Core Files ──────────────────────────────────────────
Write-Host ""
Write-Host "Step 1: Core planning files" -ForegroundColor Cyan

$coreFiles = @(
    @{ Src = "docs/plans/AI-Plan-Hardening-Runbook.md";              Dst = "docs/plans/AI-Plan-Hardening-Runbook.md" }
    @{ Src = "docs/plans/AI-Plan-Hardening-Runbook-Instructions.md"; Dst = "docs/plans/AI-Plan-Hardening-Runbook-Instructions.md" }
    @{ Src = "docs/plans/README.md";                                 Dst = "docs/plans/README.md" }
    @{ Src = "docs/plans/DEPLOYMENT-ROADMAP-TEMPLATE.md";            Dst = "docs/plans/DEPLOYMENT-ROADMAP.md" }
    @{ Src = "docs/plans/PROJECT-PRINCIPLES-TEMPLATE.md";            Dst = "docs/plans/PROJECT-PRINCIPLES-TEMPLATE.md" }
)

foreach ($f in $coreFiles) {
    $src = Join-Path $templateRoot $f.Src
    $dst = Join-Path $ProjectPath $f.Dst
    if (Test-Path $src) {
        Copy-WithCreate $src $dst $Force.IsPresent
    }
    else {
        Write-Host "  WARN  Source not found: $($f.Src)" -ForegroundColor Yellow
    }
}

# ─── Step 2: Copy Shared Instruction Files ─────────────────────────────
Write-Host ""
Write-Host "Step 2: Shared instruction files" -ForegroundColor Cyan

$sharedFiles = @(
    @{ Src = ".github/instructions/ai-plan-hardening-runbook.instructions.md"; Dst = ".github/instructions/ai-plan-hardening-runbook.instructions.md" }
    @{ Src = ".github/instructions/architecture-principles.instructions.md";   Dst = ".github/instructions/architecture-principles.instructions.md" }
    @{ Src = ".github/instructions/context-fuel.instructions.md";              Dst = ".github/instructions/context-fuel.instructions.md" }
    @{ Src = ".github/instructions/git-workflow.instructions.md";              Dst = ".github/instructions/git-workflow.instructions.md" }
    @{ Src = ".github/instructions/self-repair-reporting.instructions.md";     Dst = ".github/instructions/self-repair-reporting.instructions.md" }
    @{ Src = ".github/instructions/status-reporting.instructions.md";          Dst = ".github/instructions/status-reporting.instructions.md" }
    @{ Src = "templates/.github/instructions/project-principles.instructions.md"; Dst = ".github/instructions/project-principles.instructions.md" }
)

foreach ($f in $sharedFiles) {
    $src = Join-Path $templateRoot $f.Src
    $dst = Join-Path $ProjectPath $f.Dst
    if (Test-Path $src) {
        Copy-WithCreate $src $dst $Force.IsPresent
    }
}

# ─── Step 3: Copy Preset Files ────────────────────────────────────────
$isCustomOnly = ($Preset.Count -eq 1 -and $Preset[0] -eq 'custom')

if (-not $isCustomOnly) {
    $presetsToApply = $Preset | Where-Object { $_ -ne 'custom' }
    $isFirstPreset  = $true

    foreach ($activePreset in $presetsToApply) {
        Write-Host ""
        Write-Host "Step 3: $activePreset preset files" -ForegroundColor Cyan

        $presetDir = Join-Path $templateRoot "presets/$activePreset"
        if (-not (Test-Path $presetDir)) {
            Write-Host "  ERROR  Preset directory not found: $presetDir" -ForegroundColor Red
            exit 1
        }

        # Copy all files from preset, preserving relative paths
        Get-ChildItem -Path $presetDir -Recurse -File | ForEach-Object {
            $relativePath = $_.FullName.Substring($presetDir.Length + 1)
            $dst = Join-Path $ProjectPath $relativePath
            Copy-WithCreate $_.FullName $dst $Force.IsPresent
        }

        # First preset sets copilot-instructions.md; subsequent ones don't overwrite
        $presetCopilot = Join-Path $presetDir ".github/copilot-instructions.md"
        $rootCopilot   = Join-Path $ProjectPath ".github/copilot-instructions.md"
        if ($isFirstPreset -and (Test-Path $presetCopilot) -and -not (Test-Path $rootCopilot)) {
            Copy-WithCreate $presetCopilot $rootCopilot $Force.IsPresent
        }

        # First preset sets AGENTS.md; subsequent ones don't overwrite
        $presetAgents = Join-Path $presetDir "AGENTS.md"
        $rootAgents   = Join-Path $ProjectPath "AGENTS.md"
        if ($isFirstPreset -and (Test-Path $presetAgents) -and -not (Test-Path $rootAgents)) {
            Copy-WithCreate $presetAgents $rootAgents $Force.IsPresent
        }

        $isFirstPreset = $false
    }
}
else {
    Write-Host ""
    Write-Host "Step 3: Custom preset — copying template copilot-instructions.md only" -ForegroundColor Cyan

    $src = Join-Path $templateRoot ".github/copilot-instructions.md"
    $dst = Join-Path $ProjectPath ".github/copilot-instructions.md"
    if (Test-Path $src) {
        Copy-WithCreate $src $dst $Force.IsPresent
    }
}

# ─── Step 3b: Copy Shared Agents ───────────────────────────────────────
if (-not $isCustomOnly) {
    Write-Host ""
    Write-Host "Step 3b: Shared agents (cross-stack reviewers + pipeline agents)" -ForegroundColor Cyan

    # Shared agents (api-contract, accessibility, multi-tenancy, cicd, observability, dependency, compliance)
    $sharedAgentsDir = Join-Path $templateRoot "presets/shared/.github/agents"
    if (Test-Path $sharedAgentsDir) {
        Get-ChildItem -Path $sharedAgentsDir -Filter "*.agent.md" -File | ForEach-Object {
            $dst = Join-Path $ProjectPath ".github/agents/$($_.Name)"
            Copy-WithCreate $_.FullName $dst $Force.IsPresent
        }
    }

    # Pipeline agents (specifier, plan-hardener, executor, reviewer-gate, shipper)
    $pipelineAgentsDir = Join-Path $templateRoot "templates/.github/agents"
    if (Test-Path $pipelineAgentsDir) {
        Get-ChildItem -Path $pipelineAgentsDir -Filter "*.agent.md" -File | ForEach-Object {
            $dst = Join-Path $ProjectPath ".github/agents/$($_.Name)"
            Copy-WithCreate $_.FullName $dst $Force.IsPresent
        }
    }

    # Shared skills (health-check, forge-execute, security-audit — stack-independent fallbacks)
    # Note: Never force-overwrite — preset skills take priority over shared versions
    $sharedSkillsDir = Join-Path $templateRoot "presets/shared/skills"
    if (Test-Path $sharedSkillsDir) {
        Get-ChildItem -Path $sharedSkillsDir -Directory | ForEach-Object {
            $skillName = $_.Name
            $skillSrc  = Join-Path $_.FullName "SKILL.md"
            $skillDst  = Join-Path $ProjectPath ".github/skills/$skillName/SKILL.md"
            if (Test-Path $skillSrc) {
                Copy-WithCreate $skillSrc $skillDst $false
            }
        }
    }
}

# ─── Step 3c: Copy Project Principles Prompt + Extension Templates + Hooks ─────
if (-not $isCustomOnly) {
    Write-Host ""
    Write-Host "Step 3c: Project Principles prompt + extension templates + hooks" -ForegroundColor Cyan

    # Project Principles prompt
    $ppPromptSrc = Join-Path $templateRoot "templates/.github/prompts/project-principles.prompt.md"
    $ppPromptDst = Join-Path $ProjectPath ".github/prompts/project-principles.prompt.md"
    if (Test-Path $ppPromptSrc) {
        Copy-WithCreate $ppPromptSrc $ppPromptDst $Force.IsPresent
    }

    # Pipeline prompts (step0-step6 + project-profile) from repo .github/prompts/
    $pipelinePromptsSrc = Join-Path $templateRoot ".github/prompts"
    if (Test-Path $pipelinePromptsSrc) {
        Get-ChildItem -Path $pipelinePromptsSrc -Filter "*.prompt.md" -File | ForEach-Object {
            # Skip project-principles.prompt.md — already handled from templates/ above
            if ($_.Name -eq 'project-principles.prompt.md') { return }
            $dst = Join-Path $ProjectPath ".github/prompts/$($_.Name)"
            Copy-WithCreate $_.FullName $dst $Force.IsPresent
        }
    }

    # Extension template directory
    $extTemplateSrc = Join-Path $templateRoot "templates/.forge"
    if (Test-Path $extTemplateSrc) {
        Get-ChildItem -Path $extTemplateSrc -Recurse -File | ForEach-Object {
            $relativePath = $_.FullName.Substring($extTemplateSrc.Length + 1)
            $dst = Join-Path $ProjectPath ".forge/$relativePath"
            Copy-WithCreate $_.FullName $dst $Force.IsPresent
        }
    }

    # Hooks
    $hooksSrc = Join-Path $templateRoot "templates/.github/hooks"
    if (Test-Path $hooksSrc) {
        Get-ChildItem -Path $hooksSrc -Recurse -File | ForEach-Object {
            $relativePath = $_.FullName.Substring($hooksSrc.Length + 1)
            $dst = Join-Path $ProjectPath ".github/hooks/$relativePath"
            Copy-WithCreate $_.FullName $dst $Force.IsPresent
        }
    }
}

# ─── Step 3d: Install Extensions (if requested) ─────────────────────
if ($InstallExtensions) {
    $extDir = Join-Path $ProjectPath ".forge/extensions"
    if (Test-Path $extDir) {
        Write-Host ""
        Write-Host "Step 3d: Installing extensions" -ForegroundColor Cyan

        Get-ChildItem -Path $extDir -Directory | Where-Object {
            Test-Path (Join-Path $_.FullName "extension.json")
        } | ForEach-Object {
            $extFullName = $_.FullName
            $manifest = Get-Content (Join-Path $extFullName "extension.json") -Raw | ConvertFrom-Json
            Write-Host "  Installing: $($manifest.name) v$($manifest.version)" -ForegroundColor Magenta

            @('instructions', 'agents', 'prompts') | ForEach-Object {
                $srcSubDir = Join-Path $extFullName $_
                if (Test-Path $srcSubDir) {
                    $destBase = Join-Path $ProjectPath ".github/$_"
                    Get-ChildItem -Path $srcSubDir -File | ForEach-Object {
                        $dst = Join-Path $destBase $_.Name
                        Copy-WithCreate $_.FullName $dst $Force.IsPresent
                    }
                }
            }

            # Merge MCP server config if extension declares one
            if ($manifest.files.mcp) {
                $mcpSrc = Join-Path $extFullName $manifest.files.mcp
                if (Test-Path $mcpSrc) {
                    $mcpDst = Join-Path $ProjectPath ".vscode/mcp.json"
                    $mcpSrcJson = Get-Content $mcpSrc -Raw | ConvertFrom-Json

                    if (Test-Path $mcpDst) {
                        $mcpDstJson = Get-Content $mcpDst -Raw | ConvertFrom-Json
                        if (-not $mcpDstJson.servers) {
                            $mcpDstJson | Add-Member -NotePropertyName 'servers' -NotePropertyValue ([PSCustomObject]@{}) -Force
                        }
                        foreach ($serverName in $mcpSrcJson.servers.PSObject.Properties.Name) {
                            if (-not $mcpDstJson.servers.PSObject.Properties[$serverName]) {
                                $mcpDstJson.servers | Add-Member -NotePropertyName $serverName -NotePropertyValue $mcpSrcJson.servers.$serverName -Force
                                Write-Host "  MERGE  .vscode/mcp.json → added '$serverName' server" -ForegroundColor Green
                            }
                            else {
                                Write-Host "  SKIP   .vscode/mcp.json → '$serverName' server already exists" -ForegroundColor Yellow
                            }
                        }
                        $mcpDstJson | ConvertTo-Json -Depth 10 | Set-Content $mcpDst
                    }
                    else {
                        $vscodeDir = Join-Path $ProjectPath ".vscode"
                        if (-not (Test-Path $vscodeDir)) {
                            New-Item -ItemType Directory -Path $vscodeDir -Force | Out-Null
                        }
                        Copy-Item $mcpSrc $mcpDst
                        Write-Host "  CREATE .vscode/mcp.json" -ForegroundColor Green
                    }
                }
            }
        }
    }
}

# ─── Step 4: Replace Placeholders ─────────────────────────────────────
Write-Host ""
Write-Host "Step 4: Replacing placeholders" -ForegroundColor Cyan

Get-ChildItem -Path $ProjectPath -Recurse -Include "*.md" -File | ForEach-Object {
    Update-Placeholders $_.FullName $ProjectName $stackLabel
}

Write-Host "  DONE  Placeholders replaced" -ForegroundColor Green

# ─── Step 5: Generate .forge.json ─────────────────────────────
Write-Host ""
Write-Host "Step 5: Generating .forge.json" -ForegroundColor Cyan

$configPath = Join-Path $ProjectPath ".forge.json"
$versionFile = Join-Path $templateRoot "VERSION"
$templateVersion = if (Test-Path $versionFile) { (Get-Content $versionFile -Raw).Trim() } else { "1.0.0" }

# Phase-26 Slice 14 — best-defaults preset writer.
# We only write when `.forge.json` is absent so upgrades never clobber a
# user-customized config. The preset intentionally keeps every Phase-26
# inner-loop subsystem in an ADVISORY posture: detection runs, but no action
# is taken without an explicit opt-in.
function Write-BestDefaultsPreset {
    param(
        [string]$Path,
        [string]$ProjectName,
        [object]$Preset,
        [object]$Agents,
        [string]$StackLabel,
        [string]$TemplateVersion
    )
    $cfg = @{
        projectName     = $ProjectName
        preset          = if ($Preset.Count -eq 1) { $Preset[0] } else { $Preset }
        agents          = if ($Agents.Count -eq 1) { $Agents[0] } else { $Agents }
        stack           = $StackLabel
        setupDate       = (Get-Date -Format 'yyyy-MM-dd')
        templateVersion = $TemplateVersion
        modelRouting    = @{ default = "claude-opus-4.6" }
        hooks           = @{
            preDeploy        = @{ blockOnSecrets = $true; warnOnEnvGaps = $true; scanSince = "HEAD~1" }
            postSlice        = @{ silentDeltaThreshold = 5; warnDeltaThreshold = 10; scoreFloor = 70 }
            preAgentHandoff  = @{ injectContext = $true; runRegressionGuard = $true; cacheMaxAgeMinutes = 30; minAlertSeverity = "medium" }
        }
        # Phase-26 defaults — all advisory, zero destructive action by default.
        innerLoop       = @{
            competitive  = @{ enabled = $false }  # worktree races are opt-in; off by default
            autoFix      = @{ enabled = $true; applyWithoutReview = $false }  # detect & draft patches, never auto-apply
            costAnomaly  = @{ enabled = $true; ratio = 2.0; medianWindow = 20 }  # advisory only
        }
        brain           = @{
            federation = @{ enabled = $false; repos = @() }  # off by default; opt-in per repo
        }
    } | ConvertTo-Json -Depth 5
    Set-Content -Path $Path -Value $cfg
}

if (Test-Path $configPath) {
    Write-Host "  SKIPPED  .forge.json already exists (preserving user config)" -ForegroundColor Yellow
} else {
    Write-BestDefaultsPreset -Path $configPath `
        -ProjectName $ProjectName -Preset $Preset -Agents $agents `
        -StackLabel $stackLabel -TemplateVersion $templateVersion
    Write-Host "  CREATED  .forge.json (best-defaults preset)" -ForegroundColor Green
}

# ─── Step 5a: Create docs/plans/auto/ for LiveGuard fix proposals ────
$autoPlansDir = Join-Path $ProjectPath "docs/plans/auto"
if (-not (Test-Path $autoPlansDir)) {
    New-Item -ItemType Directory -Path $autoPlansDir -Force | Out-Null
}
$autoReadme = Join-Path $autoPlansDir "README.md"
if (-not (Test-Path $autoReadme)) {
    Set-Content -Path $autoReadme -Value @"
# Auto-Generated Plans

This directory contains plans auto-generated by LiveGuard tools (e.g. ``forge_fix_proposal``).

Files in this directory (except this README) are gitignored — they are runtime artifacts, not source-controlled plans.
"@
}
Write-Host "  CREATED  docs/plans/auto/" -ForegroundColor Green

# ─── Step 5b: Generate capabilities.json (machine-readable discovery) ────
$capabilitiesPath = Join-Path $ProjectPath ".forge/capabilities.json"
$promptsDir  = Join-Path $ProjectPath ".github/prompts"
$agentsDir   = Join-Path $ProjectPath ".github/agents"
$skillsDir   = Join-Path $ProjectPath ".github/skills"

$promptFiles = @()
if (Test-Path $promptsDir) {
    $promptFiles = Get-ChildItem -Path $promptsDir -Filter "*.prompt.md" -File | ForEach-Object { $_.Name }
}
$agentFiles = @()
if (Test-Path $agentsDir) {
    $agentFiles = Get-ChildItem -Path $agentsDir -Filter "*.agent.md" -File | ForEach-Object { $_.Name }
}
$skillFiles = @()
if (Test-Path $skillsDir) {
    $skillFiles = Get-ChildItem -Path $skillsDir -Recurse -Filter "SKILL.md" -File | ForEach-Object {
        $_.Directory.Name
    }
}

$capabilities = @{
    generatedBy = "plan-forge-setup"
    generatedAt = (Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')
    preset      = $Preset
    prompts     = $promptFiles
    agents      = $agentFiles
    skills      = $skillFiles
    instructions = @()
    hooks       = @(".github/hooks/plan-forge.json")
}

$instrDir = Join-Path $ProjectPath ".github/instructions"
if (Test-Path $instrDir) {
    $capabilities.instructions = Get-ChildItem -Path $instrDir -Filter "*.instructions.md" -File | ForEach-Object { $_.Name }
}

$capDir = Split-Path $capabilitiesPath -Parent
if (!(Test-Path $capDir)) { New-Item -ItemType Directory -Path $capDir -Force | Out-Null }
$capabilities | ConvertTo-Json -Depth 3 | Set-Content -Path $capabilitiesPath
Write-Host "  CREATED  .forge/capabilities.json" -ForegroundColor Green

# ─── Step 6: Copy VS Code Settings Template ────────────────────────────
Write-Host ""
Write-Host "Step 6: VS Code settings template" -ForegroundColor Cyan

$vscodeSrc = Join-Path $templateRoot "templates/vscode-settings.json.template"
$vscodeDst = Join-Path $ProjectPath ".vscode/settings.json"
if (Test-Path $vscodeSrc) {
    Copy-WithCreate $vscodeSrc $vscodeDst $Force.IsPresent
}

# ─── Step 6b: Install Agent Adapters ───────────────────────────────────
$agents = $Agent
if ($agents -contains 'all') {
    $agents = @('copilot', 'claude', 'cursor', 'windsurf', 'codex', 'gemini', 'generic')
}
# Copilot files are already installed (the default). Only run adapters for others.
$extraAgents = $agents | Where-Object { $_ -ne 'copilot' }

if ($extraAgents.Count -gt 0) {
    Write-Host ""
    Write-Host "Step 6b: Agent adapters ($($extraAgents -join ', '))" -ForegroundColor Cyan

    foreach ($ag in $extraAgents) {
        switch ($ag) {
            'claude'    { Install-ClaudeAgent $ProjectPath }
            'cursor'    { Install-CursorAgent $ProjectPath }
            'windsurf'  { Install-WindsurfAgent $ProjectPath }
            'codex'     { Install-CodexAgent $ProjectPath }
            'gemini'    { Install-GeminiAgent $ProjectPath }
            'generic'   { Install-GenericAgent $ProjectPath $GenericDir }
        }
    }
}

# ─── Step 7: Copy Copilot VS Code Guide ────────────────────────────────
$guideSrc = Join-Path $templateRoot "docs/COPILOT-VSCODE-GUIDE.md"
$guideDst = Join-Path $ProjectPath "docs/COPILOT-VSCODE-GUIDE.md"
if (Test-Path $guideSrc) {
    Copy-WithCreate $guideSrc $guideDst $Force.IsPresent
}

# ─── Step 7b: Copy MCP Server + Generate Config ───────────────────────
$mcpSrcDir = Join-Path $templateRoot "pforge-mcp"
if (Test-Path $mcpSrcDir) {
    Write-Host ""
    Write-Host "Step 7b: MCP server (Plan Forge as tools)" -ForegroundColor Cyan

    $mcpDstDir = Join-Path $ProjectPath "pforge-mcp"
    if (-not (Test-Path $mcpDstDir)) {
        New-Item -ItemType Directory -Path $mcpDstDir -Force | Out-Null
    }

    # Copy all MCP runtime files (not node_modules or .forge)
    $mcpFileCount = 0
    Get-ChildItem -Path $mcpSrcDir -File -Recurse |
        Where-Object { $_.FullName -notmatch '(node_modules|\.forge|coverage)' } |
        ForEach-Object {
            $relPath = $_.FullName.Substring($mcpSrcDir.Length + 1)
            $dstFile = Join-Path $mcpDstDir $relPath
            $dstParent = Split-Path $dstFile -Parent
            if (-not (Test-Path $dstParent)) { New-Item -ItemType Directory -Path $dstParent -Force | Out-Null }
            Copy-Item -Path $_.FullName -Destination $dstFile -Force
            $mcpFileCount++
        }
    Write-Host "  COPY  pforge-mcp/ ($mcpFileCount files: server, orchestrator, capabilities, dashboard, tests)" -ForegroundColor Green

    # Generate .vscode/mcp.json for Copilot MCP integration
    $vscodeMcp = Join-Path $ProjectPath ".vscode/mcp.json"
    $mcpEntry = @{
        servers = @{
            "plan-forge" = @{
                type = "stdio"
                command = "node"
                args = @("pforge-mcp/server.mjs")
                cwd = '${workspaceFolder}'
            }
        }
    }

    if (Test-Path $vscodeMcp) {
        $existing = Get-Content $vscodeMcp -Raw | ConvertFrom-Json
        if (-not $existing.servers.PSObject.Properties["plan-forge"]) {
            $existing.servers | Add-Member -NotePropertyName "plan-forge" -NotePropertyValue $mcpEntry.servers."plan-forge" -Force
            $existing | ConvertTo-Json -Depth 10 | Set-Content $vscodeMcp
            Write-Host "  MERGE .vscode/mcp.json → added 'plan-forge' server" -ForegroundColor Green
        }
        else {
            Write-Host "  SKIP  .vscode/mcp.json → 'plan-forge' already exists" -ForegroundColor Yellow
        }
        # Add forge-master-chat server entry if pforge-master/server.mjs exists
        $fmServer = Join-Path $ProjectPath "pforge-master/server.mjs"
        if ((Test-Path $fmServer) -and -not $existing.servers.PSObject.Properties["forge-master-chat"]) {
            $fmEntry = @{
                type    = "stdio"
                command = "node"
                args    = @("pforge-master/server.mjs")
                cwd     = '${workspaceFolder}'
            }
            $existing2 = Get-Content $vscodeMcp -Raw | ConvertFrom-Json
            $existing2.servers | Add-Member -NotePropertyName "forge-master-chat" -NotePropertyValue $fmEntry -Force
            $existing2 | ConvertTo-Json -Depth 10 | Set-Content $vscodeMcp
            Write-Host "  MERGE .vscode/mcp.json → added 'forge-master-chat' server" -ForegroundColor Green
        }
    }
    else {
        $vscodeDir = Join-Path $ProjectPath ".vscode"
        if (-not (Test-Path $vscodeDir)) { New-Item -ItemType Directory -Path $vscodeDir -Force | Out-Null }
        $mcpEntry | ConvertTo-Json -Depth 10 | Set-Content $vscodeMcp
        Write-Host "  CREATE .vscode/mcp.json (plan-forge MCP server)" -ForegroundColor Green
    }

    # Generate .claude/mcp.json for Claude MCP integration (if -Agent claude)
    if ($agents -contains 'claude' -or $agents -contains 'all') {
        $claudeMcpDir = Join-Path $ProjectPath ".claude"
        $claudeMcp = Join-Path $claudeMcpDir "mcp.json"
        if (-not (Test-Path $claudeMcpDir)) { New-Item -ItemType Directory -Path $claudeMcpDir -Force | Out-Null }
        if (-not (Test-Path $claudeMcp)) {
            $mcpEntry | ConvertTo-Json -Depth 10 | Set-Content $claudeMcp
            Write-Host "  CREATE .claude/mcp.json (plan-forge MCP server)" -ForegroundColor Green
        }
    }

    # Auto-install MCP dependencies
    $mcpPkgJson = Join-Path $mcpDstDir "package.json"
    if (Test-Path $mcpPkgJson) {
        Write-Host "  Installing MCP dependencies..." -ForegroundColor DarkCyan
        try {
            $npmOutput = & npm install --prefix $mcpDstDir 2>&1
            Write-Host "  ✅ npm install complete" -ForegroundColor Green
        } catch {
            Write-Host "  ⚠️  npm install failed — run manually: cd pforge-mcp && npm install" -ForegroundColor Yellow
        }
    }
}

# ─── Step 7c: Copy CLI Scripts + VERSION ──────────────────────────────
Write-Host ""
Write-Host "Step 7c: CLI scripts" -ForegroundColor Cyan

foreach ($cliFile in @("pforge.ps1", "pforge.sh", "VERSION")) {
    $cliSrc = Join-Path $templateRoot $cliFile
    $cliDst = Join-Path $ProjectPath $cliFile
    if (Test-Path $cliSrc) {
        Copy-Item -Path $cliSrc -Destination $cliDst -Force
        Write-Host "  COPY  $cliFile" -ForegroundColor Green
    }
}

# ─── Done ──────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║                    Setup Complete!                          ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "Files installed to: $ProjectPath" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Review .github/copilot-instructions.md — fill in project-specific details"
Write-Host "  2. Review AGENTS.md — customize worker patterns for your app"
Write-Host "  3. Review .vscode/settings.json — uncomment instruction file references"
Write-Host "  4. Review .github/prompts/ — customize scaffolding recipes for your conventions"
Write-Host "  5. Review .github/agents/ — tailor reviewer checklists for your project"
Write-Host "  6. Review .github/skills/ — update build/deploy commands for your CI/CD"
Write-Host "  7. Review docs/plans/DEPLOYMENT-ROADMAP.md — add your phases"
Write-Host "  8. Read docs/COPILOT-VSCODE-GUIDE.md for Copilot Agent Mode workflow"
Write-Host "  9. Start planning: open docs/plans/AI-Plan-Hardening-Runbook-Instructions.md"
Write-Host ""
Write-Host "Optional (recommended):" -ForegroundColor Yellow
Write-Host "  - Run .github/prompts/project-profile.prompt.md to generate project-specific guardrails"
Write-Host "  - Run .github/prompts/project-principles.prompt.md to define project principles"
Write-Host "  - Use .github/prompts/step0-specify-feature.prompt.md to define your first feature"
Write-Host "  - Start your first plan the Crucible way: call forge_crucible_submit (MCP) — every plan ships with a crucibleId for full traceability" -ForegroundColor DarkCyan
Write-Host "  - On GitHub? Run 'pforge github status' for a GitHub-native readiness check, or read /manual/plan-forge-on-the-github-stack.html" -ForegroundColor DarkCyan
Write-Host ""

# ─── Step 7.5: OpenBrain L3 Memory Prompt (Phase-OPENBRAIN-PROMOTION Slice 4) ──
# Plan Forge ships with L1 (Hub) + L2 (.forge/*.jsonl) memory built in. The L3 layer
# — cross-session, cross-tool, semantic-search memory — requires OpenBrain. Optional
# but recommended. Prompt only fires in interactive TTY runs.
#
# Skip gates (any one suppresses the prompt):
#   - $NonInteractive switch
#   - $env:CI (set by GitHub Actions, GitLab CI, Azure DevOps, CircleCI, etc.)
#   - $env:PFORGE_NONINTERACTIVE (Plan Forge — internal automation flag)
#   - Host RawUI is $null (running under a non-interactive host)
$skipOpenBrainPrompt = $NonInteractive `
    -or $env:CI `
    -or $env:PFORGE_NONINTERACTIVE `
    -or -not $Host.UI.RawUI

if ($skipOpenBrainPrompt) {
    Write-Host "i Skipping OpenBrain prompt (non-interactive / CI). Run 'pforge brain hint' anytime to revisit." -ForegroundColor DarkGray
    Write-Host ""
}
else {
    Write-Host "================================================================" -ForegroundColor Cyan
    Write-Host " Recommended: Enable Persistent Memory (OpenBrain)" -ForegroundColor Cyan
    Write-Host "================================================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Plan Forge ships with L1 (Hub) + L2 (.forge/*.jsonl) memory."
    Write-Host "The L3 layer — cross-session semantic memory that powers Reflexion"
    Write-Host "lessons, Auto-skills, and cross-project Federation — requires"
    Write-Host "OpenBrain, a self-hosted MCP server. Plan Forge works without it,"
    Write-Host "but the inner loop only improves over time when L3 is present."
    Write-Host ""
    $obResp = try { Read-Host "Show me OpenBrain install options? [Y/n/skip]" } catch { "skip" }

    if ($obResp -match '^(n|no)$') {
        Write-Host ""
        Write-Host "!  Skipping. Reflexion / Auto-skills / Federation will be inert. Re-enable anytime with 'pforge brain hint'." -ForegroundColor Yellow
        Write-Host ""
    }
    elseif ($obResp -match '^(s|skip)$') {
        Write-Host ""
        Write-Host "i Skipped. Re-enable anytime with 'pforge brain hint'." -ForegroundColor DarkGray
        Write-Host ""
    }
    else {
        # Empty or any other input → default Y branch.
        Write-Host ""
        Write-Host "OpenBrain deploy options:" -ForegroundColor Yellow
        Write-Host "  - Docker Compose       ~5 min   Free                Local dev / single machine"
        Write-Host "  - Supabase Cloud       ~10 min  ~`$0.10-`$0.30/mo     Solo / small team, zero ops"
        Write-Host "  - Kubernetes / Azure   ~30 min  Cloud rates         Teams, federation across repos"
        Write-Host ""
        Write-Host "Full walkthrough:  https://srnichols.github.io/OpenBrain" -ForegroundColor Cyan
        Write-Host "Source repo:       https://github.com/srnichols/OpenBrain" -ForegroundColor DarkGray
        Write-Host ""
        Write-Host "After installing, run 'pforge brain status' to confirm Plan Forge sees it." -ForegroundColor Green
        Write-Host ""
    }
}

# ─── Step 8: Auto-validate ─────────────────────────────────────────────
Write-Host "Running validation..." -ForegroundColor Cyan
$validateScript = Join-Path $templateRoot "validate-setup.ps1"
if (Test-Path $validateScript) {
    & $validateScript -ProjectPath $ProjectPath
}
