import { execSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, basename, resolve } from "node:path";
import { PROJECT_DIR, FRAMEWORK_VERSION } from "./state.mjs";

function _formatOrgRulesOutput(format, sections, header, timestamp) {
  if (format === "json") {
    const repoLine = header.split("repo: ")[1] || "";
    const versionLine = header.split("v")[1]?.split(" ")[0] || "";
    return JSON.stringify({ repo: repoLine, version: versionLine, generated: new Date().toISOString(), sections }, null, 2);
  }
  if (format === "markdown") {
    const parts = [header, timestamp, ""];
    for (const { section, entries } of sections) {
      parts.push(`## ${section}`, "");
      for (const { title, body } of entries) {
        parts.push(`### ${title}`, "", body, "");
      }
    }
    return parts.join("\n").trimEnd();
  }
  // github format — plain text for GitHub org custom instructions
  const parts = [header, timestamp, ""];
  for (const { section, entries } of sections) {
    parts.push(`=== ${section} ===`, "");
    for (const { body } of entries) {
      parts.push(body, "");
    }
  }
  return parts.join("\n").trimEnd();
}

// ─── Org Rules Consolidation ──────────────────────────────────────────
export function callOrgRules({ format = "github", output: outputFile = null } = {}, cwd = PROJECT_DIR) {
  const instrDir = join(cwd, ".github", "instructions");
  const copilotFile = join(cwd, ".github", "copilot-instructions.md");
  const principlesFile = join(cwd, "PROJECT-PRINCIPLES.md");

  const instrFiles = existsSync(instrDir)
    ? readdirSync(instrDir).filter((f) => f.endsWith(".instructions.md")).sort().map((f) => join(instrDir, f))
    : [];

  let repoName = basename(cwd);
  try {
    const gitRemote = execSync("git remote get-url origin 2>/dev/null || true", { cwd, encoding: "utf-8", timeout: 5_000 }).trim();
    if (gitRemote) repoName = gitRemote.split("/").pop().replace(/\.git$/, "");
  } catch { /* keep folder name */ }

  const versionFile = join(cwd, "VERSION");
  // Issue #106: when cwd is a sub-tree without a VERSION file, fall back to
  // the install's own VERSION instead of a stale literal.
  const version = existsSync(versionFile)
    ? readFileSync(versionFile, "utf-8").trim()
    : FRAMEWORK_VERSION;

  function stripFrontmatter(raw) {
    const stripped = raw.replace(/^---[\s\S]*?---\s*/m, "").trim();
    const titleMatch = stripped.match(/^#\s+(.+)/m);
    const title = titleMatch ? titleMatch[1].trim() : null;
    const body = stripped.replace(/^#\s+.+\n?/m, "").trim();
    return { title, body };
  }

  const SECTION_PATTERNS = [
    { section: "Architecture Principles", pattern: /architect|design|layer|separation/i },
    { section: "Git Workflow",            pattern: /git|commit|branch|workflow/i },
    { section: "Security Rules",          pattern: /security|auth|secret|permission/i },
    { section: "Testing Requirements",    pattern: /test|spec|coverage/i },
    { section: "Coding Standards",        pattern: /./ },
  ];

  function categorise(filePath) {
    const name = basename(filePath);
    for (const { section, pattern } of SECTION_PATTERNS) {
      if (pattern.test(name)) return section;
    }
    return "Coding Standards";
  }

  const grouped = {};
  for (const f of instrFiles) {
    const sec = categorise(f);
    if (!grouped[sec]) grouped[sec] = [];
    grouped[sec].push(f);
  }

  const sections = [];
  const sectionOrder = ["Architecture Principles", "Coding Standards", "Git Workflow", "Security Rules", "Testing Requirements"];
  for (const sec of sectionOrder) {
    if (!grouped[sec]?.length) continue;
    const entries = grouped[sec].map((f) => {
      const raw = readFileSync(f, "utf-8");
      const { title, body } = stripFrontmatter(raw);
      return { file: basename(f), title: title || basename(f).replace(/\.instructions\.md$/, ""), body };
    });
    sections.push({ section: sec, entries });
  }

  if (existsSync(copilotFile)) {
    const raw = readFileSync(copilotFile, "utf-8");
    const { title, body } = stripFrontmatter(raw);
    sections.push({ section: "Project Context", entries: [{ file: "copilot-instructions.md", title: title || "Project Context", body }] });
  }

  if (existsSync(principlesFile)) {
    const raw = readFileSync(principlesFile, "utf-8");
    const { title, body } = stripFrontmatter(raw);
    sections.push({ section: "Project Principles", entries: [{ file: "PROJECT-PRINCIPLES.md", title: title || "Project Principles", body }] });
  }

  const header = `# Generated by Plan Forge v${version} from repo: ${repoName}`;
  const timestamp = `# Generated: ${new Date().toISOString()}`;
  const output = _formatOrgRulesOutput(format, sections, header, timestamp);

  if (outputFile) {
    const outPath = resolve(cwd, outputFile);
    writeFileSync(outPath, output, "utf-8");
    return `Org rules exported to: ${outPath}\n\n${output}`;
  }

  return output;
}
